with open("agents/reporting_agent.py", "w") as f:
    f.write("import os, json\nfrom datetime import datetime, timezone\n")
    f.write("try:\n    from infrastructure.database import get_db_manager, neo4j_session\n")
    f.write("except:\n    neo4j_session = None; get_db_manager = None\n")
    f.write("class ReportingAgent:\n    def __init__(self, agent_id='rep'):\n")
    f.write("        self.agent_id = agent_id; self.name = 'Reporting Agent'\n")
    f.write("    def execute_task(self, payload):\n")
    f.write("        ts = datetime.now(timezone.utc).isoformat()\n")
    f.write("        rid = payload.get('run_id', 'run_unk'); rd = f'reports/live_runs/{rid}'\n")
    f.write("        os.makedirs(rd, exist_ok=True)\n")
    f.write("        try:\n            if get_db_manager:\n                m = get_db_manager()\n")
    f.write("                if hasattr(m, 'initialize'): m.initialize()\n")
    f.write("                elif hasattr(m, 'connect'): m.connect()\n        except: pass\n")
    f.write("        imp = payload.get('impact', {}).get('findings', [])\n")
    f.write("        res = payload.get('research', {}).get('research', [])\n")
    f.write("        val = payload.get('validation', {}).get('validations', [])\n")
    f.write("        tr = payload.get('traces', {}); vn = []\n")
    f.write("        if neo4j_session:\n            try:\n                with neo4j_session() as s:\n")
    f.write("                    for f_i in imp:\n")
    f.write("                        s.run(\"MERGE (b:LegislativeItem {bill_id:$b,run_id:$r}) SET b.title=$t,b.reason_for_score=$rs,b.agent_id=$a,b.source=$src,b.swarm_id='affirm_policy_swarm',b.project_scope='affirm_bnpl_policy'\", {'b':f_i.get('bill_id',''),'r':rid,'t':f_i.get('title',''),'rs':f_i.get('reason_for_score',''),'a':self.agent_id,'src':f_i.get('source','')})\n")
    f.write("                    r = s.run(\"MATCH (b:LegislativeItem) WHERE b.run_id=$r RETURN b.bill_id AS b, b.source AS s\", {'r':rid})\n")
    f.write("                    for row in r: vn.append({'bill_id':row['b'], 'source':row['s']})\n")
    f.write("            except: pass\n")
    f.write("        tr['ReportingAgent'] = {'agent_id':self.agent_id,'agent_name':self.name,'status':'COMPLETED'}\n")
    f.write("        with open(f'{rd}/agent_trace.json', 'w') as f: json.dump(tr, f, indent=2)\n")
    f.write("        with open(f'{rd}/report.json', 'w') as f: json.dump({'run_id':rid,'findings':imp,'research_context':res,'validation':val,'neo4j_readback':{'matched':len(vn)}}, f, indent=2)\n")
    f.write("        with open(f'{rd}/neo4j_readback.json', 'w') as f: json.dump({'run_id':rid,'fresh_records_read_back':len(vn),'nodes':[x['bill_id'] for x in vn]}, f, indent=2)\n")
    f.write("        ld = [{'source':f_i.get('source'),'bill_id':f_i.get('bill_id'),'title':f_i.get('title'),'evidence_snippets':[f_i.get('reason_for_score')],'run_id':rid} for f_i in imp]\n")
    f.write("        with open(f'{rd}/evidence_ledger.json', 'w') as f: json.dump(ld, f, indent=2)\n")
    f.write("        md = f'# 🚀 Swarm Intelligence Report\\n\\n## 📌 Metadata\\n* **Run ID:** `{rid}`\\n\\n## 🧠 Live Findings & Agent Reasoning\\n\\n'\n")
    f.write("        rm = {r.get('bill_id'):r for r in res if 'bill_id' in r}\n")
    f.write("        vm = {v.get('bill_id'):v for v in val if 'bill_id' in v}\n")
    f.write("        for f_i in imp:\n            b = f_i.get('bill_id', ''); r_i = rm.get(b, {}); v_i = vm.get(b, {})\n")
    f.write("            md += f\"### {f_i.get('title','')}\\n* **ID / Source:** `{b}` | {f_i.get('source','')}\\n\"\n")
    f.write("            md += f\"* **Impact Reasoning:** {f_i.get('reason_for_score','')}\\n\"\n")
    f.write("            md += f\"* **Research Context:** {r_i.get('research_notes','No lookup.')}\\n\"\n")
    f.write("            md += f\"* **Validation:** {v_i.get('validation_status','')} - {v_i.get('validation_reason','')}\\n---\\n\\n\"\n")
    f.write("        md += f'## 🛢️ Neo4j Read-Back\\n* Nodes: `{len(vn)}`\\n'\n")
    f.write("        with open(f'{rd}/report.md', 'w') as f: f.write(md)\n")
    f.write("        return {'report_dir': rd}\n")
